### ISSUE TITLE
Can't compile on ArchLinux

### ISSUE THREAD

**Issue by essen** [barrel-db/barrel#5]
===> Compiling couch
make[1]: Entering directory '/home/essen/tmp/barrel/_build/default/lib/couch/c_src/couch_js'
cc -c -DXP_UNIX -I/usr/include/js /home/essen/tmp/barrel/_build/default/lib/couch/c_src/couch_js/http.c
/home/essen/tmp/barrel/_build/default/lib/couch/c_src/couch_js/http.c:19:19: fatal error: jsapi.h: No such file or directory
compilation terminated.
Makefile:44: recipe for target '/home/essen/tmp/barrel/_build/default/lib/couch/c_src/couch_js/http.o' failed
make[1]: *** [/home/essen/tmp/barrel/_build/default/lib/couch/c_src/couch_js/http.o] Error 1
make[1]: Leaving directory '/home/essen/tmp/barrel/_build/default/lib/couch/c_src/couch_js'
===> Hook for compile failed!

The file is located at /usr/include/js-17.0/jsapi.h

Probably won't have time to look further in the next two weeks.

**Comment by nrdufour** [comment]
Oh I know how to fix that: I have arch on the udoo :) The thing you need to do is to install the package `js185` and it will work like a charm! Have fun!

**Comment by essen** [comment]
Works fine now, thanks!
