### ISSUE TITLE
previously working erlang couch_native_process fails

### ISSUE THREAD

**Issue by davidoccam** [barrel-db/barrel#6]
previously working erlang couch_native_process fails with an error message that cannot be copied so I had to try to attach a screenshot 

![barrel_erlang](https://cloud.githubusercontent.com/assets/478806/8508556/fa09a7b6-226c-11e5-9db7-9785b587ebc6.png)

running on Linux raspberrypi2 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux

**Comment by benoitc** [comment]
that's an interresting one. Working on it.

- benoit

**Comment by davidoccam** [comment]
[<0.26109.1>] [info] 192.168.0.102 - - GET /y_combinator-tests2 /_design/erlang4/_view/y-comb5?limit=11&descending=true&group=true 500

[<0.26109.1>] [error] httpd 500 error response:

 {"error":"EXIT","reason":"{{badmatch,[]},
 [{couch_query_servers,new_process,3,
  [{file,\"/home/pi/barrel-alpha-2 /_build/default/lib/couch/src/couch_query_servers.erl\"},{line,476}]},
 {couch_query_servers,lang_proc,3,                     
[{file,\"/home/pi/barrel-alpha-2 /_build/default/lib/couch/src/couch_query_servers.erl\"},                        {line,466}]},
 {couch_query_servers,handle_call,3, [{file,\"/home/pi/barrel-alpha-2 /_build/default/lib/couch/src/couch_query_servers.erl\"},                        {line,341}]},
{gen_server,try_handle_call,4,[{file,\"gen_server.erl\"},{line,607}]},  {gen_server,handle_msg,5,[{file,\"gen_server.erl\"},{line,639}]},  {proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,237}]}]}"
}
 lines  in couch_query_servers.erl

"{Lang, Lim, Current}] = ets:lookup(LangLimits, Lang),"  

       " case (catch new_process(Langs, LangLimits, Lang)) of
        {ok, Proc} ->
            add_value(PidProcs, Proc#proc.pid, Proc),
            PickFun([Proc]);
        ErrorOrWait ->
            ErrorOrWait
        end"

There does not seem to be an ETS called Langlimits according to Observer

![no langlimits_table](https://cloud.githubusercontent.com/assets/478806/8508910/8e41c3ea-227d-11e5-854f-eecdb54497b1.png)

**Comment by benoitc** [comment]
@davidoccam do you have any error before in the logs?

**Comment by benoitc** [comment]
@davidoccam somehow it looks like you have no query servers defined. Did you try to call a view before, or was it the first time?

**Comment by davidoccam** [comment]
@davidoccam do you have any error before in the logs? no.

@davidoccam somehow it looks like you have no query servers defined. Did you try to call a view before, or was it the first time?
First time for erlang view.


crash.log
2015-07-04 20:44:46 UTC =ERROR REPORT====
Error in process <0.6944.0> on node 'barrel@rcouchpi' with exit value: 
 {{nocatch,{'EXIT',{{badmatch,[]},[{couch_query_servers,new_process,3,
[{file,"/home/pi/barrel-alpha-2/_build/default/lib/couch/src/couch_query_servers.erl"},
{line,476}]},{couch_query_servers,lang_proc,3,[{file,"/home/...

couch.log same error as above 

Javascript query server shown below <9868.1031.0>
No Erlang query server ever appears

![couch_processes](https://cloud.githubusercontent.com/assets/478806/8509388/a85f5f8e-2297-11e5-9d2e-2a957f00e7c6.png)

**Comment by davidoccam** [comment]
By "previously working"  I mean previously working on other instances of rcouch/couch. Not previously working on barrel.

**Comment by benoitc** [comment]
ah. The erlang view server is handled like any other query server in
barrel. Or rather all view servers are now handled the same. It should be
set in the query_servers section. I will try later in the morning.

Not that the error is ok though. it should rather return a 400 and not
crash others view servers. Also it should be better documented.

Let me know if you went further.

**Comment by davidoccam** [comment]
I had in local.ini
[native_query_servers]
erlang = {couch_native_process, start_link, []}

It recognised Erlang source code in Futon dropdown and looked to be O.K

but it needed something like this?

[query_servers]
javascript =  {couch_couchjs, start_link, ["/home/pi/barrel-alpha-2 /_build/prod/rel/barrel/share/server/main.js"]}
coffeescript = {couch_couchjs, start_link, ["/home/pi/barrel-alpha-2 /_build/prod/rel/barrel/share/server/main-coffee.js"]}


erlang = {???, start_link,[???]}

We live and learn.

**Comment by benoitc** [comment]
yes it should work that way now. So adding a langage is just a matter to
bind it in erlang.

**Comment by davidoccam** [comment]
enter in local or couch ini file.
[query_servers]
erlang = {couch_native_process, start_link, []}

comparison of erlang view generation and javascript view generation over 22527 schools in England 
on a Raspberrypi2 running Barrel.

![erlang_view_generation](https://cloud.githubusercontent.com/assets/478806/8512301/879e2a4e-2334-11e5-9be8-8386541d9853.png)
![javascript_view_generation](https://cloud.githubusercontent.com/assets/478806/8512302/8b835da0-2334-11e5-89ab-5631f1c5744f.png)

**Comment by benoitc** [comment]
the diff is impressive... Do you mind if I share it on the user forum. Imo that could be a good topic. Anyway i have a coming fix that return a 400 when the langage isn't set instead of 500. Also i started to hack on that part.

**Comment by benoitc** [comment]
i meant a good topic for what next . Barrel starting on next week will support other beams languages :)

**Comment by davidoccam** [comment]
In my opinion Couchdb development has been slanted towards software as a service (SAAS) implementation. It has thus been frightened to allow the use of its much faster native beam view generation in case it allows too much access to the core functions from those using native views.

The primary core effect of using Erlang in the first place, apart from rapid functional development, was the stability of the file system format using Erlang term storage format. 

People have endlessly tinkered with all aspects of the system re-writing it in various languages and creating massive infrastructures around it but none have really touched the real core of the original implementation fundamentals.

Erlang views have been deliberately restricted by time-outs for many years in the mainline development and yet there are many applications that would be unfeasable to perform using JavaScript, for example the heavy use of cryptographic functions as shown below.

You have my full permission to share all the images here with anyone you think will benefit from seeing them.

Erlang Map/Reduce view computing SHA512 on all fields on 22521 documents on Raspberrypi2 with 1.5Tb external disk View request duration: 00:04:20.007.

I must do a JavaScript one to see how it compares!

![sha512_over_all_fields_schools](https://cloud.githubusercontent.com/assets/478806/8513209/4d49b640-2359-11e5-9ffc-31d60987710a.png)

![result_reduced_schools](https://cloud.githubusercontent.com/assets/478806/8513147/64c4e17a-2357-11e5-8a23-2632a4bf6aaa.png)

**Comment by benoitc** [comment]
@davidoccam opened the discussion there:

 https://users.barrel-db.org/t/enable-native-views-by-default/26
