### ISSUE TITLE
Build spidermonkey statically

### ISSUE THREAD

**Issue by benoitc** [barrel-db/barrel#7]
It seems difficult still to find a correctly installed version of spidermonkey. I am wondering if we shouldn't go back for a statically linked version. Thoughts?

**Comment by Zatvobor** [comment]
Personally, I do not know much about why Spidermonkey still is Couch dependency whereas, Couchbase is already running V8 instead.

**Comment by benoitc** [comment]
Is V8 shipped on all distributions now? I knew couchbase was v8 but it's only for M/R. And the thing is that barrel will support and improve the CouchAPPS or UPApps (unreliable platform of apps) . So we need supports for any transform function like shows, lists, update functions, Also filters. So we will need to add it, if we want to support the couchapp. Note that eventually couchapps could be shipped appart from the index so we could eventually support a view engine // from the couchapp engine.

The other thing is that the v8 implementation in couchbase is a NIF which under load may be an issue, blocking the scheduler.

Maybe if we go to v8 we could just **embed nodejs in a port**? an implementation is available in couchdb, but I am not a fan of it, it could be a lot simpler. Maybe this the way to go. also could offer some interresting opportunities to extend the couchapps easily.

About **spidermonkey** , either servo, or firefox are building it statically. Basho does the same in erlang_js so I gues we should also do the same :)

**Comment by Zatvobor** [comment]
Ok, here is my point of view about the future roadmap of rcouch and further steps. 
I wanna to see rcouch as a framework for building a couch-like appliances (with wide range of target platforms and usage purpose) based on reusable components.

Fast facts here:

##### rcouch/couch 

- should not have any kind of js dependencies and related assets.

##### rcouch/couch_mrview (or maybe `couch_designdocs`)

- `couch_query_servers` and `couch_native_process` should be here
- erlang language for design docs by default

##### rcouch/couch_js_query_server

- js dependencies such as (couchjs, couch_js_functions.hrl and others)
- spidermonkey driver by default
- ability to tweak another driver, for instance, v8 (maybe as a part of `somebody/couch_v8_query_server`)

There is one more important question here about unit and acceptance testing (both erlang and js tests). Still don't have a clear vision (I'm still working on that). 
That is another topic and I'll send you an issue.

**Comment by nrdufour** [comment]
I like that idea yes. I never realized until recently the power of those erlang based views. And it should clearly be the default one.
I know js is attracting because most people know it, but it's not difficult either to learn a bit of erlang to use the views.

As for v8/spidermonkey, if we can manage to create a v8 one, then why bother keeping the spidermonkey one around?

**Comment by benoitc** [comment]
@Zatvobor I am working exactly on such separation of concerns. Still juggling with some modules and the way the config at the end could work with each but hopefully will have something to show tomorrow :)

@nrdufour because the v8 one doesn't exist yet :) Like I said the couchbase code is only about M/R and doesn't handle the couchapps features. Also I am not a fan of using a nif there since it can easily block the scheduler but for some usage it can be useful.

**Comment by Zatvobor** [comment]
nice. Let me know what can I help you with it as I pleased to contribute.

**Comment by benoitc** [comment]
@Zatvobor wip in #11 :)

**Comment by benoitc** [comment]
4ad181e62c212181a4228fb779beac47fcd1df97 is actually solving this ticket. So i will close it.

About other concerns, the view server will be pluggable in another release of barrel. I will create a ticket for it.
