### ISSUE TITLE
Alpha-2: Test Suite for Run All raises a ton of unauthorized errors

### ISSUE THREAD

**Issue by Zatvobor** [barrel-db/barrel#9]
The 'Test Suite' raises a ton of unauthorized errors which comes from server as many of 401 responses under Admin Party mode. 

On the other hands, after clicking on 'Reload' button and press 'Run All' again, the page says: `Error: You need to be an admin to run the tests.` and Admin Party is gone )

Does someone experience the same or this is just only my local issue?

**Comment by benoitc** [comment]
@Zatvobor just reproduced it. It seems that the users database is not correctly created. .I am working on it. Expect a fix in the afternoon.

**Comment by benoitc** [comment]
maybe related to #10

**Comment by Zatvobor** [comment]
Well done )
